services:
    app:
        build:
            context: ./
            dockerfile: .docker/8.2/Dockerfile
        command: 'php artisan serve --host 0.0.0.0 --port 8000'
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www/html'
        networks:
            - backend
networks:
    backend:
        driver: bridge
